name = "travel-map-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_als"]

[vars]
ENVIRONMENT = "production"

[version_metadata]
binding = "CF_VERSION_METADATA"
