name = "travel-map-api"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_als"]

[vars]
ENVIRONMENT = "production"

# KV namespace for caching GeoJSON data
[[kv_namespaces]]
binding = "GEO_CACHE"
id = "9fd75a23f8fa4511870de8c1d98b7cf3"
preview_id = "02658687ae2d40ac8a5fb486f86c2858"

[version_metadata]
binding = "CF_VERSION_METADATA"
